pipeline {
    agent any
    environment {
        PROJECT_ID = 'YOUR_GCP_PROJECT_ID' // We will fill this later
        REGION = 'us-central1'
        REPO_NAME = 'jenkins-repo'
        IMAGE_NAME = 'flask-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }
        stage('Push to Artifact Registry') {
            steps {
                // This is where the WIF magic happens
                sh "gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet"
                sh "docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
        stage('Deploy to GKE') {
            steps {
                sh "sed -i 's|IMAGE_PLACEHOLDER|${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}|g' k8s/deployment.yaml"
                sh "kubectl apply -f k8s/deployment.yaml"
            }
        }
    }
}