pipeline {
    agent any
    environment {
        PROJECT_ID = 'cloud-run-490411' 
        REGION = 'asia-south1'
        REPO_NAME = 'gke-repo'
        IMAGE_NAME = 'flask-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Deploy') {
            steps {
                // This tells Jenkins: "Go into this folder and run everything inside the brackets"
                dir('jenkins-gke-project') {
                    
                    script {
                        echo "Building Docker Image..."
                        sh "docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG} ."
                        
                        echo "Pushing to Artifact Registry..."
                        sh "gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet"
                        sh "docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}"
                        
                        echo "Deploying to GKE..."
                        sh "sed -i 's|IMAGE_PLACEHOLDER|${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG}|g' k8s/deployment.yaml"
                        sh "kubectl apply -f k8s/deployment.yaml"
                    }
                }
            }
        }
    }
}