apiVersion: v1
kind: Service
metadata:
  name: my-app-service-staging
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080