steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/cloud-run-490411/my-app-repo/my-app-image',
      '-f',
      'Cloud-build/Dockerfile',
      'Cloud-build'
    ]

  # Step 2: Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-south1-docker.pkg.dev/cloud-run-490411/my-app-repo/my-app-image'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'my-flask-app',
      '--image', 'asia-south1-docker.pkg.dev/cloud-run-490411/my-app-repo/my-app-image',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-south1-docker.pkg.dev/cloud-run-490411/my-app-repo/my-app-image'

options:
 logging: CLOUD_LOGGING_ONLY
