# name: CI Pipeline

# on:
#   push:
#     paths:
#       - 'gke-github-actions-demo/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Build Docker Image
#         run: |
#           cd gke-github-actions-demo
#           docker build -t demo-image .


name: CI Pipeline

on:
  push:
    paths:
      - 'gke-github-actions-demo/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for WIF

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/640095824150/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@cloud-run-490411.iam.gserviceaccount.com"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          cd gke-github-actions-demo
          docker build -t asia-south1-docker.pkg.dev/cloud-run-490411/gke-repo/demo-image:latest .

      - name: Push Docker Image
        run: |
          docker push asia-south1-docker.pkg.dev/cloud-run-490411/gke-repo/demo-image:latest