name: CI Pipeline

on:
  push:
    paths:
      - 'gke-github-actions-demo/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          cd gke-github-actions-demo
          docker build -t demo-image .