name: Multi-Stage GKE Deployment

on:
  push:
    branches:
      - main  # Trigger this workflow whenever code is pushed to the main branch
    paths:
      - 'github-actions-with-multi-stage/app**' # ONLY trigger if app code changes

env:
  # We use the secrets created in github
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
  SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  REGION: ${{ secrets.GCP_REGION }}
  REPOSITORY: gke-repo # This must match the name of your Artifact Registry repo
  IMAGE_NAME: node-app

jobs:
  # JOB 1: Build and Deploy to Staging
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for WIF authentication

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Image
        run: |
          # We create a unique tag using the GitHub commit SHA
          IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG ./github-actions-with-multi-stage   #should change the path according to your architecture
          docker push $IMAGE_TAG
          # Save the image tag to use in the next steps
          echo "FULL_IMAGE_NAME=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: github-actions-multi-stage # REPLACE THIS with your actual GKE Cluster Name
          location: asia-south1    # REPLACE THIS with your Cluster Zone/Region

      - name: Deploy to Staging
        run: |
          # Use 'sed' to replace the placeholder IMAGE_NAME in the yaml file with the real image tag
          sed -i "s|IMAGE_NAME|${{ env.FULL_IMAGE_NAME }}|g" github-actions-with-multi-stage/k8s-manifests/staging/deployment.yaml
          kubectl apply -f github-actions-with-multi-stage/k8s-manifests/staging/deployment.yaml   # mention the folder path as per your repo
          kubectl apply -f github-actions-with-multi-stage/k8s-manifests/staging/service.yaml      # mention the folder path as per your repo

  # JOB 2: Deploy to Production (Depends on Staging success)
  deploy-prod:
    needs: build-and-deploy-staging # Only run if the first job passed
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: github-actions-multi-stage # REPLACE THIS with your actual GKE Cluster Name
          location: asia-south1    # REPLACE THIS with your Cluster Zone/Region

      - name: Deploy to Production
        run: |
          # We reuse the same image tag from the build job
          # Since we can't easily share env variables between jobs, we reconstruct the tag
          IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          sed -i "s|IMAGE_NAME|$IMAGE_TAG|g" github-actions-with-multi-stage/k8s-manifests/prod/deployment.yaml
          kubectl apply -f github-actions-with-multi-stage/k8s-manifests/prod/deployment.yaml       # mention the folder path as per your repo
          kubectl apply -f github-actions-with-multi-stage/k8s-manifests/prod/service.yaml          # mention the folder path as per your repo